

[window]
title = "Alacritty"
blur = true
opacity = 0.93
padding.x = 5
padding.y = 5
[window.dimensions]
columns = 110
lines = 31

[cursor.style]
shape= "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "CodeNewRoman Nerd Font"
normal.style = "Bold"
size = 13.0

[font.bold]
family = "CodeNewRoman Nerd Font"
style = "Bold"

[font.italic]
family = "CodeNewRoman Nerd Font"
style = "Italic"

[general]
live_config_reload = true
working_directory = "None"
